### ISSUE TITLE
Proper Handling for subdirectory

### ISSUE THREAD

**Issue by physcocode** [Scrawler-php/Router#1]
proper way should be implemented to handle the buggy subdirectory structure url

**Comment by ystenzel** [comment]
Thanks for this nice restapi!! Sorry for opening this again, but I can't find anything on the web nor in the documentation. I try to use this restapi in a subdirectory but can't get it running. I'm not 100% sure but I think already my .htaccess is not working correct. You have some example code that is running?

**Comment by physcocode** [comment]
here is a .htaccess file used inside Scrawler Framework (A framework which this router is part of)

`RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond $1 !^(index\.php)
RewriteRule ^(.*)$ /your-sub-dir/index.php/$1 [L]
`

Just change your-sub-dir in last line to the name of your actual subdirectory
